import { Clip } from "~/editor/elma-types";

export const standardSprites = {
  apple: ["qfood1", "qfood2"],
  killer: "qkiller",
  flower: "qexit",
  kuski: [
    "q1body",
    "q1thigh",
    "q1leg",
    "q1wheel",
    "q1susp1",
    "q1susp2",
    "q1forarm",
    "q1up_arm",
    "q1head",
    "q2body",
    "q2thigh",
    "q2leg",
    "q2wheel",
    "q2susp1",
    "q2susp2",
    "q2forarm",
    "q2up_arm",
    "q2head",
    "qflag",
    "q1bike",
    "q2bike",
  ],
  misc: ["qframe", "qcolors"],
  pictures: [
    { name: "barrel", distance: 380, clip: Clip.Sky },
    { name: "bridge", distance: 400, clip: Clip.Unclipped },
    { name: "bush1", distance: 550, clip: Clip.Sky },
    { name: "bush2", distance: 550, clip: Clip.Sky },
    { name: "bush3", distance: 440, clip: Clip.Sky },
    { name: "cliff", distance: 400, clip: Clip.Sky },
    { name: "edge", distance: 440, clip: Clip.Unclipped },
    { name: "flag", distance: 450, clip: Clip.Sky },
    { name: "hang", distance: 434, clip: Clip.Sky },
    { name: "log1", distance: 420, clip: Clip.Sky },
    { name: "log2", distance: 420, clip: Clip.Sky },
    { name: "mushroom", distance: 430, clip: Clip.Sky },
    { name: "plantain", distance: 450, clip: Clip.Unclipped },
    { name: "secret", distance: 550, clip: Clip.Sky },
    { name: "sedge", distance: 430, clip: Clip.Sky },
    { name: "st3top", distance: 740, clip: Clip.Sky },
    { name: "supphred", distance: 380, clip: Clip.Sky },
    { name: "support1", distance: 380, clip: Clip.Unclipped },
    { name: "support2", distance: 380, clip: Clip.Unclipped },
    { name: "support3", distance: 380, clip: Clip.Unclipped },
    { name: "suppvred", distance: 380, clip: Clip.Sky },
    { name: "susp", distance: 380, clip: Clip.Unclipped },
    { name: "suspdown", distance: 380, clip: Clip.Unclipped },
    { name: "suspup", distance: 380, clip: Clip.Unclipped },
    { name: "tree1", distance: 550, clip: Clip.Sky },
    { name: "tree2", distance: 540, clip: Clip.Sky },
    { name: "tree3", distance: 560, clip: Clip.Sky },
    { name: "tree4", distance: 600, clip: Clip.Sky },
    { name: "tree5", distance: 600, clip: Clip.Sky },
  ],
};
