export const standardSprites = {
  apple: ["qfood1", "qfood2"],
  killer: "qkiller",
  flower: "qexit",
  kuski: [
    "q1body",
    "q1thigh",
    "q1leg",
    "q1wheel",
    "q1susp1",
    "q1susp2",
    "q1forarm",
    "q1up_arm",
    "q1head",
    "q2body",
    "q2thigh",
    "q2leg",
    "q2wheel",
    "q2susp1",
    "q2susp2",
    "q2forarm",
    "q2up_arm",
    "q2head",
    "qflag",
    "q1bike",
    "q2bike",
  ],
  other: ["qframe", "qcolors"],
};
